name: 'Release'

on:
  push: 
    branches:
      - "master"

jobs:
    push-to-registry:
      runs-on: ubuntu-latest
      timeout-minutes: 30
  
      steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Push containers to registry
        uses: ./.github/workflows/push-containers.yml